In [1]:
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

In [2]:
cleaned_filename = "digits_cleaned.csv"
df_tidy = pd.read_csv(cleaned_filename)   # encoding="utf-8" et al.
print(f"{cleaned_filename} : file read into a pandas dataframe.")
df_tidy

digits_cleaned.csv : file read into a pandas dataframe.


pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...  pix55  \
0        0     0     9    14     8     1     0     0     0     0  ...      0   
1        0     0    11    12     0     0     0     0     0     2  ...      0   
2        0     0     1     9    15    11     0     0     0     0  ...      0   
3        0     0     0     0    14    13     1     0     0     0  ...      0   
4        0     0     5    12     1     0     0     0     0     0  ...      2   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...      0   
1764     0     0     6    16    13    11     1     0     0     0  ...      0   
1765     0     0     1    11    15     1     0     0     0     0  ...      0   
1766     0     0     2    10     7     0     0     0     0     0  ...      0   
1767     0     0    10    14     8     1     0     0     0     2  ...      0   

      pix56  pix57  pix58  pix59  pix60  pix61  pix62  pix63  actual_digit  
0         0      0     11     16     15     11      1      0             8  
1         0      0      9     12     13      3      0      0             9  
2         0      0      1     10     13      3      0      0             0  
3         0      0      0      1     13     16      1      0             1  
4         0      0      3     11      8     13     12      4             2  
...     ...    ...    ...    ...    ...    ...    ...    ...           ...  
1763      0      0      2     14     15      9      0      0             9  
1764      0      0      6     16     14      6      0      0             0  
1765      0      0      2      9     13      6      0      0             8  
1766      0      0      5     12     16     12      0      0             9  
1767      0      1      8     12     14     12      1      0             8  

[1768 rows x 65 columns]

In [3]:
df_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1768 entries, 0 to 1767
Data columns (total 65 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   pix0          1768 non-null   int64
 1   pix1          1768 non-null   int64
 2   pix2          1768 non-null   int64
 3   pix3          1768 non-null   int64
 4   pix4          1768 non-null   int64
 5   pix5          1768 non-null   int64
 6   pix6          1768 non-null   int64
 7   pix7          1768 non-null   int64
 8   pix8          1768 non-null   int64
 9   pix9          1768 non-null   int64
 10  pix10         1768 non-null   int64
 11  pix11         1768 non-null   int64
 12  pix12         1768 non-null   int64
 13  pix13         1768 non-null   int64
 14  pix14         1768 non-null   int64
 15  pix15         1768 non-null   int64
 16  pix16         1768 non-null   int64
 17  pix17         1768 non-null   int64
 18  pix18         1768 non-null   int64
 19  pix19         1768 non-null

In [4]:
df_model1 = df_tidy
df_model1

pix0  pix1  pix2  pix3  pix4  pix5  pix6  pix7  pix8  pix9  ...  pix55  \
0        0     0     9    14     8     1     0     0     0     0  ...      0   
1        0     0    11    12     0     0     0     0     0     2  ...      0   
2        0     0     1     9    15    11     0     0     0     0  ...      0   
3        0     0     0     0    14    13     1     0     0     0  ...      0   
4        0     0     5    12     1     0     0     0     0     0  ...      2   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
1763     0     0     4    10    13     6     0     0     0     1  ...      0   
1764     0     0     6    16    13    11     1     0     0     0  ...      0   
1765     0     0     1    11    15     1     0     0     0     0  ...      0   
1766     0     0     2    10     7     0     0     0     0     0  ...      0   
1767     0     0    10    14     8     1     0     0     0     2  ...      0   

      pix56  pix57  pix58  pix59  pix60  pix61  pix62  pix63  actual_digit  
0         0      0     11     16     15     11      1      0             8  
1         0      0      9     12     13      3      0      0             9  
2         0      0      1     10     13      3      0      0             0  
3         0      0      0      1     13     16      1      0             1  
4         0      0      3     11      8     13     12      4             2  
...     ...    ...    ...    ...    ...    ...    ...    ...           ...  
1763      0      0      2     14     15      9      0      0             9  
1764      0      0      6     16     14      6      0      0             0  
1765      0      0      2      9     13      6      0      0             8  
1766      0      0      5     12     16     12      0      0             9  
1767      0      1      8     12     14     12      1      0             8  

[1768 rows x 65 columns]

In [5]:
COLUMNS = df_model1.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  
print(f"COL_INDEX is {COL_INDEX}\n\n")


PIXELS = [0,1,2,3,4,5,6,7,8,9]   # int to str

COLUMNS is Index(['pix0', 'pix1', 'pix2', 'pix3', 'pix4', 'pix5', 'pix6', 'pix7', 'pix8',
       'pix9', 'pix10', 'pix11', 'pix12', 'pix13', 'pix14', 'pix15', 'pix16',
       'pix17', 'pix18', 'pix19', 'pix20', 'pix21', 'pix22', 'pix23', 'pix24',
       'pix25', 'pix26', 'pix27', 'pix28', 'pix29', 'pix30', 'pix31', 'pix32',
       'pix33', 'pix34', 'pix35', 'pix36', 'pix37', 'pix38', 'pix39', 'pix40',
       'pix41', 'pix42', 'pix43', 'pix44', 'pix45', 'pix46', 'pix47', 'pix48',
       'pix49', 'pix50', 'pix51', 'pix52', 'pix53', 'pix54', 'pix55', 'pix56',
       'pix57', 'pix58', 'pix59', 'pix60', 'pix61', 'pix62', 'pix63',
       'actual_digit'],
      dtype='object')

COLUMNS[0] is pix0

COL_INDEX is {'pix0': 0, 'pix1': 1, 'pix2': 2, 'pix3': 3, 'pix4': 4, 'pix5': 5, 'pix6': 6, 'pix7': 7, 'pix8': 8, 'pix9': 9, 'pix10': 10, 'pix11': 11, 'pix12': 12, 'pix13': 13, 'pix14': 14, 'pix15': 15, 'pix16': 16, 'pix17': 17, 'pix18': 18, 'pix19': 19, 'pix20': 20, 'pix21': 21, 'pix22': 22, 'pix23'

In [6]:
A = df_model1.to_numpy()    # yields the underlying numpy array
print(A)

[[ 0  0  9 ...  1  0  8]
 [ 0  0 11 ...  0  0  9]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  1 ...  0  0  8]
 [ 0  0  2 ...  0  0  9]
 [ 0  0 10 ...  1  0  8]]


In [7]:
A = A.astype('float64')  # so many types:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A)

[[ 0.  0.  9. ...  1.  0.  8.]
 [ 0.  0. 11. ...  0.  0.  9.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  1. ...  0.  0.  8.]
 [ 0.  0.  2. ...  0.  0.  9.]
 [ 0.  0. 10. ...  1.  0.  8.]]


In [8]:
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 1768 rows and 65 cols


In [10]:
n = 42
print(f"number #{n} is {A[n]}")

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    value = A[n][i]
    print(f"  Its {colname} is {value}")

pixel_index = COL_INDEX['actual_digit']
pixel_num = int(round(A[n][pixel_index]))
pixel = PIXELS[pixel_num]
print(f"Its pixel is {pixel} (i.e., {pixel_num})")


number #42 is [ 0.  0.  0. 10. 11.  0.  0.  0.  0.  0.  9. 16.  6.  0.  0.  0.  0.  0.
 15. 13.  0.  0.  0.  0.  0.  0. 14. 10.  0.  0.  0.  0.  0.  1. 15. 12.
  8.  2.  0.  0.  0.  0. 12. 16. 16. 16. 10.  1.  0.  0.  7. 16. 12. 12.
 16.  4.  0.  0.  0.  9. 15. 12.  5.  0.  6.]
  Its pix0 is 0.0
  Its pix1 is 0.0
  Its pix2 is 0.0
  Its pix3 is 10.0
  Its pix4 is 11.0
  Its pix5 is 0.0
  Its pix6 is 0.0
  Its pix7 is 0.0
  Its pix8 is 0.0
  Its pix9 is 0.0
  Its pix10 is 9.0
  Its pix11 is 16.0
  Its pix12 is 6.0
  Its pix13 is 0.0
  Its pix14 is 0.0
  Its pix15 is 0.0
  Its pix16 is 0.0
  Its pix17 is 0.0
  Its pix18 is 15.0
  Its pix19 is 13.0
  Its pix20 is 0.0
  Its pix21 is 0.0
  Its pix22 is 0.0
  Its pix23 is 0.0
  Its pix24 is 0.0
  Its pix25 is 0.0
  Its pix26 is 14.0
  Its pix27 is 10.0
  Its pix28 is 0.0
  Its pix29 is 0.0
  Its pix30 is 0.0
  Its pix31 is 0.0
  Its pix32 is 0.0
  Its pix33 is 1.0
  Its pix34 is 15.0
  Its pix35 is 12.0
  Its pix36 is 8.0
  Its pix37 is 2.0


In [11]:
print("+++ Start of data definitions +++\n")
X_all = A[:,0:len(df_model1.columns) - 1] 
y_all = A[:,len(df_model1.columns) - 1]  

print(f"y_all (just the labels/species)   are \n {y_all}")
print(f"X_all (just the features) are \n {X_all}")


+++ Start of data definitions +++

y_all (just the labels/species)   are 
 [8. 9. 0. ... 8. 9. 8.]
X_all (just the features) are 
 [[ 0.  0.  9. ... 11.  1.  0.]
 [ 0.  0. 11. ...  3.  0.  0.]
 [ 0.  0.  1. ...  3.  0.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [13]:
# scrambling data. Remove dependence in ordering
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_labeled = X_all[indices]           
y_labeled = y_all[indices]         
print(f"The scrambled labels/species are \n {y_labeled}")
print(f"The corresponding data rows are \n {X_labeled}")


The scrambled labels/species are 
 [4. 9. 8. ... 1. 0. 6.]
The corresponding data rows are 
 [[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  5. ...  5.  0.  0.]
 [ 0.  0.  5. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 15.  0.  0.]
 [ 0.  0.  0. ...  8.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2) # random_state=42

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows\n" )

print(f"Held-out data... (testing data: {len(y_test)} rows)")
print(f"y_test: {y_test}")
print(f"X_test (first few rows): {X_test[0:5,:]}")  # 5 rows
print()
print(f"Data used for modeling... (training data: {len(y_train)} rows)")
print(f"y_train: {y_train}")
print(f"X_train (first few rows): {X_train[0:5,:]}")  # 5 rows

training with 1414 rows;  testing with 354 rows

Held-out data... (testing data: 354 rows)
y_test: [5. 0. 1. 3. 1. 4. 3. 9. 5. 5. 7. 6. 6. 1. 7. 2. 5. 4. 7. 8. 5. 5. 4. 2.
 0. 4. 4. 4. 4. 0. 2. 2. 9. 5. 5. 1. 2. 7. 6. 8. 4. 0. 4. 7. 6. 0. 2. 4.
 6. 5. 4. 1. 7. 0. 7. 1. 3. 3. 0. 4. 4. 3. 7. 4. 7. 5. 0. 7. 4. 8. 5. 0.
 6. 5. 1. 7. 9. 0. 9. 8. 1. 0. 2. 1. 1. 7. 0. 4. 9. 1. 9. 0. 6. 3. 4. 5.
 7. 0. 4. 1. 9. 4. 8. 3. 1. 6. 0. 1. 6. 1. 9. 3. 4. 5. 1. 1. 5. 3. 2. 2.
 4. 1. 1. 6. 5. 8. 4. 5. 5. 3. 8. 2. 5. 6. 7. 6. 7. 5. 6. 4. 4. 1. 9. 6.
 7. 6. 4. 7. 3. 0. 7. 5. 9. 2. 9. 5. 2. 1. 2. 5. 9. 8. 9. 0. 1. 6. 7. 2.
 3. 5. 9. 7. 4. 7. 0. 1. 7. 3. 8. 7. 3. 0. 3. 8. 9. 3. 6. 3. 7. 1. 5. 0.
 9. 9. 4. 2. 8. 2. 5. 4. 2. 7. 9. 1. 1. 5. 9. 3. 1. 9. 5. 8. 7. 6. 2. 7.
 6. 9. 9. 3. 9. 7. 9. 0. 2. 9. 9. 5. 5. 5. 0. 3. 1. 6. 8. 2. 3. 5. 9. 9.
 0. 2. 8. 3. 4. 9. 6. 9. 2. 7. 9. 0. 3. 0. 7. 3. 1. 7. 3. 1. 5. 7. 8. 9.
 1. 7. 3. 7. 5. 2. 2. 9. 8. 0. 3. 7. 6. 0. 8. 2. 6. 0. 7. 5. 9. 0. 5. 5.
 9. 9. 4. 1. 2. 8. 5. 0. 

In [15]:
from sklearn.neighbors import KNeighborsClassifier

k = 84   # PURELY A GUESS (FOR TESTING)
knn_model = KNeighborsClassifier(n_neighbors=k)    

# training
knn_model.fit(X_train, y_train)                        
print("Created and trained a knn classifier with k =", k)  

Created and trained a knn classifier with k = 84


In [16]:
predicted_labels = knn_model.predict(X_test)     
actual_labels = y_test

# print to compare...
print("Predicted labels:", predicted_labels)
print("Actual  labels  :", actual_labels)

# overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.")

Predicted labels: [5. 0. 2. 3. 1. 4. 3. 9. 5. 5. 7. 6. 6. 1. 7. 2. 5. 4. 7. 8. 5. 5. 4. 2.
 0. 4. 4. 4. 4. 0. 2. 2. 9. 5. 5. 1. 2. 7. 6. 8. 4. 0. 4. 7. 6. 0. 2. 4.
 6. 5. 4. 1. 7. 0. 7. 1. 3. 3. 0. 4. 4. 8. 7. 4. 7. 5. 0. 7. 4. 8. 5. 0.
 6. 5. 2. 7. 9. 0. 9. 8. 1. 0. 2. 1. 1. 7. 0. 4. 1. 1. 9. 0. 6. 3. 4. 5.
 7. 0. 4. 1. 9. 4. 8. 3. 1. 6. 0. 1. 6. 1. 9. 3. 4. 5. 2. 1. 5. 3. 2. 2.
 4. 1. 1. 6. 5. 8. 4. 5. 5. 3. 1. 2. 5. 6. 7. 6. 7. 9. 6. 4. 4. 1. 9. 6.
 7. 6. 4. 7. 3. 0. 7. 5. 9. 2. 9. 5. 2. 1. 2. 5. 9. 8. 9. 0. 2. 6. 7. 2.
 3. 5. 9. 7. 4. 7. 0. 2. 7. 3. 8. 7. 3. 0. 3. 8. 9. 7. 0. 3. 7. 1. 5. 0.
 9. 9. 4. 2. 8. 2. 5. 4. 2. 7. 4. 1. 1. 5. 9. 3. 1. 9. 5. 1. 7. 6. 2. 7.
 6. 9. 9. 3. 9. 7. 9. 0. 2. 9. 9. 5. 5. 5. 0. 3. 1. 6. 1. 2. 3. 5. 9. 9.
 0. 2. 8. 3. 4. 9. 6. 9. 2. 7. 9. 0. 3. 0. 7. 3. 1. 7. 3. 1. 5. 7. 8. 9.
 1. 7. 3. 7. 5. 2. 2. 9. 8. 0. 3. 7. 6. 0. 8. 2. 6. 0. 7. 5. 9. 0. 5. 5.
 1. 9. 4. 1. 2. 8. 5. 0. 0. 1. 6. 3. 6. 9. 2. 1. 7. 1. 2. 6. 4. 3. 5. 1.
 7. 8. 5. 4. 3. 4. 2. 5. 4. 1. 5.

In [17]:
# print on vertical tables

def compare_labels(predicted_labels, actual_labels):
    """ a more neatly formatted comparison """
    NUM_LABELS = len(predicted_labels)
    num_correct = 0

    print()
    print(f'row {"#":>3s} : {"predicted":>12s} {"actual":<12s}   {"result"}')   
    
    for i in range(NUM_LABELS):
        p = int(round(predicted_labels[i]))         # round protects from fp error 
        a = int(round(actual_labels[i]))
        result = "incorrect"
        if p == a:  # if they match,
            result = ""       # no longer incorrect
            num_correct += 1  # and we count a match!

        print(f"row {i:>3d} : {str(PIXELS[p]):>12s} {str(PIXELS[a]):<12s}   {result}")   

    print()
    print("Correct:", num_correct, "out of", NUM_LABELS)
    return num_correct

compare_labels(predicted_labels,actual_labels)


row   # :    predicted actual         result
row   0 :            5 5              
row   1 :            0 0              
row   2 :            2 1              incorrect
row   3 :            3 3              
row   4 :            1 1              
row   5 :            4 4              
row   6 :            3 3              
row   7 :            9 9              
row   8 :            5 5              
row   9 :            5 5              
row  10 :            7 7              
row  11 :            6 6              
row  12 :            6 6              
row  13 :            1 1              
row  14 :            7 7              
row  15 :            2 2              
row  16 :            5 5              
row  17 :            4 4              
row  18 :            7 7              
row  19 :            8 8              
row  20 :            5 5              
row  21 :            5 5              
row  22 :            4 4              
row  23 :            2 2              
row  24 :

331

In [18]:
def predictive_model( Features ):
    our_features = np.asarray([Features])               
    predicted_pixels = knn_model.predict(our_features)   # predict
    return int(predicted_pixels)

Features = [0,0,0,8,14,0,0,0,0,0,5,16,11,0,0,0,0,1,15,14,1,6,0,0,0,7,16,5,3,16,8,0,0,8,16,8,14,16,2,0,0,0,6,14,16,11,0,0,0,0,0,6,16,4,0,0,0,0,0,10,15,0,0,0]
result = predictive_model( Features )
print(f"I predict {result} from Features {Features}")

I predict 4 from Features [0, 0, 0, 8, 14, 0, 0, 0, 0, 0, 5, 16, 11, 0, 0, 0, 0, 1, 15, 14, 1, 6, 0, 0, 0, 7, 16, 5, 3, 16, 8, 0, 0, 8, 16, 8, 14, 16, 2, 0, 0, 0, 6, 14, 16, 11, 0, 0, 0, 0, 0, 6, 16, 4, 0, 0, 0, 0, 0, 10, 15, 0, 0, 0]


In [20]:
from sklearn.model_selection import cross_val_score

best_k = 84  # Not correct!
best_accuracy = 0.0  # also not correct...

for k in range(1,85):
    knn_cv_model = KNeighborsClassifier(n_neighbors=k)   # build a knn_model for every k
    cv_scores = cross_val_score( knn_cv_model, X_train, y_train, cv=5 )  # cv=5 means 80/20
    this_cv_accuracy = cv_scores.mean()               
    print(f"k: {k:2d}  cv accuracy: {this_cv_accuracy:7.4f}")

    if this_cv_accuracy > best_accuracy:  
        best_accuracy = this_cv_accuracy  # track the best accuracy
        best_k = k                        # with the best k

    
# use best_k!
print(f"best_k = {best_k}   yields the highest average cv accuracy.")  # print the best one


k:  1  cv accuracy:  0.9880
k:  2  cv accuracy:  0.9844
k:  3  cv accuracy:  0.9859
k:  4  cv accuracy:  0.9837
k:  5  cv accuracy:  0.9852
k:  6  cv accuracy:  0.9816
k:  7  cv accuracy:  0.9809
k:  8  cv accuracy:  0.9774
k:  9  cv accuracy:  0.9781
k: 10  cv accuracy:  0.9753
k: 11  cv accuracy:  0.9760
k: 12  cv accuracy:  0.9745
k: 13  cv accuracy:  0.9760
k: 14  cv accuracy:  0.9724
k: 15  cv accuracy:  0.9724
k: 16  cv accuracy:  0.9703
k: 17  cv accuracy:  0.9717
k: 18  cv accuracy:  0.9710
k: 19  cv accuracy:  0.9689
k: 20  cv accuracy:  0.9682
k: 21  cv accuracy:  0.9668
k: 22  cv accuracy:  0.9675
k: 23  cv accuracy:  0.9668
k: 24  cv accuracy:  0.9661
k: 25  cv accuracy:  0.9632
k: 26  cv accuracy:  0.9646
k: 27  cv accuracy:  0.9646
k: 28  cv accuracy:  0.9646
k: 29  cv accuracy:  0.9618
k: 30  cv accuracy:  0.9625
k: 31  cv accuracy:  0.9597
k: 32  cv accuracy:  0.9569
k: 33  cv accuracy:  0.9547
k: 34  cv accuracy:  0.9547
k: 35  cv accuracy:  0.9533
k: 36  cv accuracy: 

In [21]:
best_k = best_k   # not needed, but nice
from sklearn.neighbors import KNeighborsClassifier
knn_model_tuned = KNeighborsClassifier(n_neighbors=best_k)   # use the best_k

# we train the model (one line!)
knn_model_tuned.fit(X_train, y_train)  
print(f"Created + trained a knn classifier, now tuned with a (best) k of {best_k}")  


Created + trained a knn classifier, now tuned with a (best) k of 1


In [23]:
predicted_labels = knn_model_tuned.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)

# And, the overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.\n\n")

# print our nicer table
compare_labels(predicted_labels,actual_labels)

Predicted labels: [5. 0. 1. 3. 1. 4. 3. 9. 5. 5. 7. 6. 6. 1. 7. 2. 5. 4. 7. 8. 5. 5. 4. 2.
 0. 4. 4. 4. 4. 0. 2. 2. 8. 5. 5. 1. 2. 7. 6. 8. 4. 0. 4. 7. 6. 0. 2. 4.
 6. 5. 4. 1. 7. 0. 7. 1. 3. 3. 0. 4. 4. 3. 7. 4. 7. 5. 0. 7. 4. 8. 5. 0.
 6. 5. 1. 7. 9. 0. 9. 8. 1. 0. 2. 1. 1. 7. 0. 4. 9. 1. 9. 0. 6. 3. 4. 5.
 7. 0. 4. 1. 9. 4. 8. 3. 1. 6. 0. 1. 6. 1. 9. 3. 4. 5. 1. 1. 5. 3. 2. 2.
 4. 1. 1. 6. 5. 8. 4. 5. 5. 3. 8. 2. 5. 6. 7. 6. 7. 5. 6. 4. 4. 1. 9. 6.
 7. 6. 4. 7. 3. 0. 7. 5. 9. 2. 9. 5. 2. 1. 2. 5. 9. 8. 9. 0. 1. 6. 7. 2.
 3. 5. 9. 7. 4. 7. 0. 1. 7. 3. 8. 7. 3. 0. 3. 8. 9. 3. 6. 3. 7. 1. 5. 0.
 9. 9. 4. 2. 8. 2. 5. 4. 2. 7. 9. 1. 1. 5. 9. 3. 1. 9. 5. 8. 7. 6. 2. 7.
 6. 9. 9. 3. 9. 7. 9. 0. 2. 9. 9. 5. 5. 5. 0. 3. 1. 6. 8. 2. 3. 5. 9. 9.
 0. 2. 8. 3. 4. 9. 6. 9. 2. 7. 9. 0. 3. 0. 7. 3. 1. 7. 3. 1. 5. 7. 8. 9.
 1. 7. 3. 7. 5. 2. 2. 9. 8. 0. 3. 7. 6. 0. 8. 2. 6. 0. 7. 5. 9. 0. 5. 5.
 9. 9. 4. 1. 2. 8. 5. 0. 0. 1. 6. 3. 6. 9. 2. 4. 7. 1. 2. 6. 4. 3. 5. 1.
 7. 3. 5. 4. 3. 4. 2. 5. 4. 1. 3.

351

In [24]:
knn_model_final = KNeighborsClassifier(n_neighbors=best_k)     # here, we use the best_k
knn_model_final.fit(X_all, y_all)                              
print(f"Created + trained a 'final' knn classifier, with a (best) k of {best_k}") 

Created + trained a 'final' knn classifier, with a (best) k of 1


In [26]:
def predictive_model( Features, Model ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    predicted_species = Model.predict(our_features)       # The model's prediction
    predicted_species = int(round(predicted_species[0]))  # unpack the extra brackets
    return predicted_species
   
LoF = [[0,0,0,8,14,0,0,0,0,0,5,16,11,0,0,0,0,1,15,14,1,6,0,0,0,7,16,5,3,16,8,0,0,8,16,8,14,16,2,0,0,0,6,14,16,11,0,0,0,0,0,6,16,4,0,0,0,0,0,10,15,0,0,0],
[0,0,0,5,14,12,2,0,0,0,7,15,8,14,4,0,0,0,6,2,3,13,1,0,0,0,0,1,13,4,0,0,0,0,1,11,9,0,0,0,0,8,16,13,0,0,0,0,0,5,14,16,11,2,0,0,0,0,0,6,12,13,3,0],
[0,0,0,3,16,3,0,0,0,0,0,12,16,2,0,0,0,0,8,16,16,4,0,0,0,7,16,15,16,12,11,0,0,8,16,16,16,13,3,0,0,0,0,7,14,1,0,0,0,0,0,6,16,0,0,0,0,0,0,4,14,0,0,0],
[0,0,0,3,15,10,1,0,0,0,0,11,10,16,4,0,0,0,0,12,1,15,6,0,0,0,0,3,4,15,4,0,0,0,0,6,15,6,0,0,0,4,15,16,9,0,0,0,0,0,13,16,15,9,3,0,0,0,0,4,9,14,7,0],
[0,0,0,3,16,3,0,0,0,0,0,10,16,11,0,0,0,0,4,16,16,8,0,0,0,2,14,12,16,5,0,0,0,10,16,14,16,16,11,0,0,5,12,13,16,8,3,0,0,0,0,2,15,3,0,0,0,0,0,4,12,0,0,0],
[0,0,7,15,15,4,0,0,0,8,16,16,16,4,0,0,0,8,15,8,16,4,0,0,0,0,0,10,15,0,0,0,0,0,1,15,9,0,0,0,0,0,6,16,2,0,0,0,0,0,8,16,8,11,9,0,0,0,9,16,16,12,3,0]]

# run on each one:
for Features in LoF:
    predicted_species = predictive_model( Features, knn_model_final )  
    name = PIXELS[predicted_species]
    print(f"I predict {name} from the features {Features}") 

I predict 4 from the features [0, 0, 0, 8, 14, 0, 0, 0, 0, 0, 5, 16, 11, 0, 0, 0, 0, 1, 15, 14, 1, 6, 0, 0, 0, 7, 16, 5, 3, 16, 8, 0, 0, 8, 16, 8, 14, 16, 2, 0, 0, 0, 6, 14, 16, 11, 0, 0, 0, 0, 0, 6, 16, 4, 0, 0, 0, 0, 0, 10, 15, 0, 0, 0]
I predict 2 from the features [0, 0, 0, 5, 14, 12, 2, 0, 0, 0, 7, 15, 8, 14, 4, 0, 0, 0, 6, 2, 3, 13, 1, 0, 0, 0, 0, 1, 13, 4, 0, 0, 0, 0, 1, 11, 9, 0, 0, 0, 0, 8, 16, 13, 0, 0, 0, 0, 0, 5, 14, 16, 11, 2, 0, 0, 0, 0, 0, 6, 12, 13, 3, 0]
I predict 4 from the features [0, 0, 0, 3, 16, 3, 0, 0, 0, 0, 0, 12, 16, 2, 0, 0, 0, 0, 8, 16, 16, 4, 0, 0, 0, 7, 16, 15, 16, 12, 11, 0, 0, 8, 16, 16, 16, 13, 3, 0, 0, 0, 0, 7, 14, 1, 0, 0, 0, 0, 0, 6, 16, 0, 0, 0, 0, 0, 0, 4, 14, 0, 0, 0]
I predict 2 from the features [0, 0, 0, 3, 15, 10, 1, 0, 0, 0, 0, 11, 10, 16, 4, 0, 0, 0, 0, 12, 1, 15, 6, 0, 0, 0, 0, 3, 4, 15, 4, 0, 0, 0, 0, 6, 15, 6, 0, 0, 0, 4, 15, 16, 9, 0, 0, 0, 0, 0, 13, 16, 15, 9, 3, 0, 0, 0, 0, 4, 9, 14, 7, 0]
I predict 4 from the features [0, 0, 0, 3, 16,

<br>

#### Digit-recognition experiments:

In [29]:
def masked_digits(pixel_num):
    """ Takes in a list of pixel values returns another list with pixel_num number of elements/pixels"""

    from sklearn.model_selection import train_test_split
    from sklearn.model_selection import cross_val_score
    from sklearn.neighbors import KNeighborsClassifier

    X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=0.2) # random_state=42

    X_train = X_train[:,:pixel_num] # We want pixel_num amount of pixels...
    X_test = X_test[:,:pixel_num] # We want pixel_num amount of pixels...
    y_train = y_train # These do not change since we still want all possible output digits
    y_test = y_test # These do not change since we still want all possible output digits
    
    best_k = 42  # Not correct!
    best_accuracy = 0.0  # also not correct...

    # Note that we are cross-validating using only our TEST data!
    for k in range(1,43):
        knn_cv_model = KNeighborsClassifier(n_neighbors=k)   # build a knn_model for every k
        cv_scores = cross_val_score( knn_cv_model, X_train, y_train, cv=5 )  # cv=5 means 80/20
        this_cv_accuracy = cv_scores.mean()               # mean() is numpy's built-in average function 
        # print(f"k: {k:2d}  cv accuracy: {this_cv_accuracy:7.4f}")

        if this_cv_accuracy > best_accuracy:  # is this one better?
            best_accuracy = this_cv_accuracy  # track the best accuracy
            best_k = k                        # with the best k


    best_k = best_k   # not needed, but nice
    knn_model_tuned = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k!

    # we train the model (one line!)
    knn_model_tuned.fit(X_train, y_train)                              # yay!  trained!

    predicted_labels = knn_model_tuned.predict(X_test)
    actual_labels = y_test

    # And, the overall results
    num_correct = sum(predicted_labels == actual_labels)
    total = len(actual_labels)
    testing_accuracy = num_correct / total
    # print(f"\nResults on test set:  {num_correct} correct out of {total} total.\n\n")

    # this is the output we want to insert in our table
    return best_k, testing_accuracy
    
    
    

masked_digits(42)


(1, 0.9548022598870056)

In [30]:
# importing required library
# got this code online (https://www.geeksforgeeks.org/generate-simple-ascii-tables-using-prettytable-in-python/)
# make sure to install PrettyTable
from prettytable import PrettyTable
# import PrettyTable
  
# creating an empty PrettyTable
x = PrettyTable()
  
# adding data into the table
# row by row
x.field_names = ["How Many Pixels to Use", "Best_K", "Testing Accuracy"]
for i in range(8, 65):
    print('working on iteration', i)
    values = masked_digits(i)
    x.add_row([f'{i}', f'{values[0]}', f'{values[1]}'])

# printing generated table
# Open in text editor to see full results
print(x)

working on iteration 8
working on iteration 9
working on iteration 10
working on iteration 11
working on iteration 12
working on iteration 13
working on iteration 14
working on iteration 15
working on iteration 16
working on iteration 17
working on iteration 18
working on iteration 19
working on iteration 20
working on iteration 21
working on iteration 22
working on iteration 23
working on iteration 24
working on iteration 25
working on iteration 26
working on iteration 27
working on iteration 28
working on iteration 29
working on iteration 30
working on iteration 31
working on iteration 32
working on iteration 33
working on iteration 34
working on iteration 35
working on iteration 36
working on iteration 37
working on iteration 38
working on iteration 39
working on iteration 40
working on iteration 41
working on iteration 42
working on iteration 43
working on iteration 44
working on iteration 45
working on iteration 46
working on iteration 47
working on iteration 48
working on iterati